### ISSUE TITLE
Simultaneous Testing 3 - Chain Template details should be created by only Logistics Coordinator and Admin.

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#39]
Logistics Coordinator should be allowed to edit the chain template. The chain template that the canvasser used in the JO can't be edited by Logistics Coordinator therefore the JO can't move forward to either forwarder or site receiver.

**Expected behavior**
Chain template must be editable by the Logistics Coordinator.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HannahCastro** [comment]
Due to this issue, receiving was impossible as the Chain Template was defaulted. We tried to look for the account of the forwarder but we can't find it.
![image](https://user-images.githubusercontent.com/51902789/64304929-4af8ca80-cfc0-11e9-8700-5157ed768b15.png)
![image](https://user-images.githubusercontent.com/51902789/64304948-5946e680-cfc0-11e9-9c24-536888a09b93.png)

**Comment by LAValera** [comment]
LC can edit the chain template after JO is assigned already.
