### ISSUE TITLE
TS109:The clock icon on top of the Date Needed at Site form is not available. This was available before to indicate that the PTH can input/change the Date Needed at Site.

### ISSUE THREAD

**Issue by LAValera** [vasavah/vsv-fli-grn#80]
**Describe the bug**
(PTH Access) The clock icon on top of the Date Needed at Site form is not available. This was available before to indicate that the PTH can input/change the Date Needed at Site.

**To Reproduce**
-After creation of PO and JO
-In the PTH access, view the PO
-View the JO
-Go to the Date Needed at Site form
-See error

**Expected behavior**
The clock icon should be available for the PTH to change the Date Needed at Site if within the 14 days from JO creation.

**Screenshots**
![image](https://user-images.githubusercontent.com/54824392/65096765-b5662d80-d9f8-11e9-9217-5e9529a10ee5.png)

**Desktop (please complete the following information):**
 - Device: [Desktop]
 - OS: [Windows 7]
 - Browser [Chrome]
 - Version 77.0.3865.75 (Official Build) (64-bit)

**Comment by HannahCastro** [comment]
On top of this, since the clock icon is missing, PTH/PIC can no longer change Date Needed at Site. They can only confirm it. If PTH/PIC decides to change the Date Needed at Site, they need to indicate reason for changing the date before system proceeds with the changes.
![image](https://user-images.githubusercontent.com/51902789/65474137-4df32680-dead-11e9-9687-61cd2aa90770.png)

**Comment by LAValera** [comment]
Clock icon is available to trigger the form where PTH can set date needed on site.
